# netlify.toml

[functions]
  # This tells Netlify where to find your serverless functions.
  # It MUST match the directory in your repository.
  directory = "src/netlify/functions/"

[build]
  # This tells Netlify what command to run to build your site.
  # This is likely already set in your Netlify UI, but it's good practice to have it here.
  command = "npm run build"
  # This tells Netlify where the final static site files are after the build.
  publish = "dist"
[build.environment]
  NETLIFY_PRERENDER_ENABLED = "true"
